a = int(input())
b = int(input()) 
c = int(input())
d = int(input())
e = int(input())
f = int(input())
g = int(input())
h = int(input())
i = int(input())
j = int(input())
k = int(input())
l = int(input())
m = int(input())
n = int(input())
o = int(input())
p = int(input())
if a+b+c+d+e+f+g+h == i+j+k+l+m+n+o+p:
    print ("NO")
else:
    print("YES")